WebsiteHocAVOnline/Areas/ADmin/Controllers/SystemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebsiteHocAVOnline.Models;

namespace WebsiteHocAVOnline.Areas.ADmin.Controllers
{
    public class SystemController : Controller
    {
        // GET: ADmin/System
        DBThiTrucTuyenEntities db = new DBThiTrucTuyenEntities();

        #region Quản Lý

        public ActionResult Index()
        {
            return View(db.Admins.ToList());
        }
        [HttpGet]
        public ActionResult AddAccount() // Thêm tài khoản quản trị
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddAccount(Admin adGet)
        {
            //Session["AD_ADMIN"] = 1;
            try
            {
                db.Admins.Add(adGet);

                db.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        [HttpGet]
        public ActionResult DelAccount()
        {
            return View();
        }

        [HttpPost]
        public ActionResult DelAccount(int id)
        {
            Admin _id = db.Admins.Find(id);

            db.Admins.Remove(_id);

            db.SaveChanges();

            return RedirectToAction("Index");

         }

        [HttpGet]
        public ActionResult EditAccount(int id)
        {
            return View(db.Admins.Where(Model => Model.ID == id).FirstOrDefault());
        }


        public ActionResult EditAccount(Admin adGet)
        {
            var adList = db.Admins.Where(Model => Model.ID == adGet.ID).FirstOrDefault();

            adList.TenTK = adGet.TenTK;

            adList.MatKhau = adGet.MatKhau;

            db.SaveChanges();
            return RedirectToAction("Index");
        }

        #endregion

        #region Đăng nhập - Đăng xuất 

        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }


        [HttpPost]
        public ActionResult Login(FormCollection form)
        {
            string taikhoan = form["taikhoan"].ToString();

            string matkhau = form["matkhau"].ToString();

            Admin adminVar = db.Admins.Where(Model => Model.TenTK == taikhoan && Model.MatKhau == matkhau).SingleOrDefault();

            if (adminVar != null)
            {
                Session["ADMIN"] = adminVar.ID;

                return RedirectToAction("Index", "Home");
            }
            else
            {
                ViewBag.Error = "* Sai tài khoản hoặc mật khẩu!";
            }

            return View();
        }


        public ActionResult Logout()
        {
            Session.Remove("ADMIN");

            Session.Abandon();

            return RedirectToAction("Login");
        }

        #endregion
    }
}

WebsiteHocAVOnline/Areas/ADmin/Views/System/AddAccount.cshtml
@model WebsiteHocAVOnline.Models.Admin

@{
    ViewBag.Title = "AddAccount";
    Layout = "~/Areas/ADmin/Views/Shared/_Layout.cshtml";
}

    <div class="row">

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>Thêm Tài Khoản Quản Trị Viên</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.TenTK, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.TenTK, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.TenTK, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.MatKhau, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.MatKhau, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.MatKhau, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Thêm" class="btn btn-primary btn-sm btn-block" />
                    </div>
                </div>
            </div>
        }
    </div>

WebsiteHocAVOnline/Areas/ADmin/Views/System/EditAccount.cshtml
@model WebsiteHocAVOnline.Models.Admin

@{
    ViewBag.Title = "EditAccount";
    Layout = "~/Areas/ADmin/Views/Shared/_Layout.cshtml";
}

<div class="row">

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Thay Đổi Tài Khoản Quản Trị Viên</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.ID)

            <div class="form-group">
                @Html.LabelFor(model => model.TenTK, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.TenTK, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TenTK, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.MatKhau, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.MatKhau, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.MatKhau, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

WebsiteHocAVOnline/Areas/ADmin/Views/System/Index.cshtml
@using WebsiteHocAVOnline.Models;
@model List<Admin>

@{
    Layout = "~/Areas/ADmin/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-lg-12">
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <a href="/ADmin/System/AddAccount" class="btn btn-danger btn-xs pull-right"><b>+</b> Thêm mới</a>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>STT</th>
                                <th>Mã tài khoản</th>
                                <th>Tài Khoản</th>
                                <th>Mật khẩu</th>
                                <th class="text-center">Quản lý</th>
                            </tr>

                        </thead>

                        @{
                            int i = 0;

                            foreach (var item in Model)
                            {
                                i++;
                                using (Html.BeginForm("DelAccount", "System", new { id = item.ID }))
                                {

                                    <tr>

                                        <td>@i</td>
                                        <td>@item.ID</td>
                                        <td>@item.TenTK</td>
                                        <td>******</td>
                                        <td class="text-center">

                                            <a href="/ADmin/System/EditAccount?id=@item.ID" class="btn btn-danger btn-xs"> Sửa</a>
                                            |
                                            <input type="submit" value="Xóa" class="btn btn-danger btn-xs" onclick="return confirm('Bạn có muốn xóa tài khoản: @item.TenTK ?')" />

                                        </td>

                                    </tr>

                                }

                            }

                        }

                    </table>

                </div>


            </div>
          </div>
      </div>
</div>

WebsiteHocAVOnline/Areas/ADmin/Views/System/Login.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>OnLine-Test-AV Admin</title>

    <!-- Custom fonts for this template-->
    <link href="~/Assets/ADmin/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="~/Assets/Admin/css/sb-admin-2.min.css" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

    <div class="container">

        <!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
                            <div class="col-lg-6">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h1 class="h4 text-gray-900 mb-4">Welcome to Admin mode!</h1>
                                    </div>
                                    @using (Html.BeginForm("Login", "System", FormMethod.Post, new { @class = "form-horizontal" }))
                                    {
                                        <fieldset>
                                            <p class="text-danger">@ViewBag.Error</p>
                                            <div class="form-group">
                                                <div class="col-md-12">
                                                    <div class="input-group">
                                                        <span class="input-group-addon">
                                                            <i class="glyphicon glyphicon-user"></i>
                                                        </span> <input name="taikhoan" placeholder="Tên đăng nhập" class="form-control"
                                                                       type="text">
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <div class="col-md-12">
                                                    <div class="input-group">
                                                        <span class="input-group-addon">
                                                            <i class="glyphicon glyphicon-lock"></i>
                                                        </span> <input name="matkhau" placeholder="Mật khẩu" class="form-control" type="password">
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="form-group">
                                                <div class="col-md-12">
                                                    <button type="submit" class="btn btn-primary btn-sm btn-block">Đăng nhập </button>
                                                </div>
                                            </div>

                                        </fieldset>
                                    }
                                </div>

                            </div>

                        </div>
                     </div>
                    </div>
                </div>

            </div>
        </div>
</body>

</html>