WebsiteHocAVOnline/Areas/ADmin/Controllers/LearnController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebsiteHocAVOnline.Models;

namespace WebsiteHocAVOnline.Areas.ADmin.Controllers
{
    public class LearnController : Controller
    {
        // GET: ADmin/Learn
        DBThiTrucTuyenEntities db = new DBThiTrucTuyenEntities();

        public ActionResult Index(int page = 1, int pageSize = 8)
        {

            if (Session["ADMIN"] == null)
            {
                return RedirectToAction("Login");
            }

            Learnning learning = new Learnning();

            var model = learning.NumberPagePagination(page, pageSize);

            return View(model);
        }

        [HttpGet]
        public ActionResult AddLearn()
        {

            if (Session["ADMIN"] == null)
            {
                return RedirectToAction("Login");
            }

            List<Category> list = db.Categories.ToList();

            ViewBag.List = new SelectList(list, "ID_Category", "TênCategory");

            return View();
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult AddLearn(Learning leGet)
        {
            if (Session["ADMIN"] == null)
            {
                return RedirectToAction("Login");
            }

            List<Category> list = db.Categories.ToList();

            ViewBag.List = new SelectList(list, "ID_Category", "TênCategory");

            try
            {
                db.Learnings.Add(leGet);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }

        }

        [HttpPost]
        public ActionResult DelLearn(int id)
        {
            Learning _id = db.Learnings.Find(id);

            db.Learnings.Remove(_id);

            db.SaveChanges();

            return RedirectToAction("Index");
        }


        [HttpGet]
        public ActionResult EditLearn(int id)
        {
            List<Category> list = db.Categories.ToList();

            ViewBag.List = new SelectList(list, "ID_Category", "TênCategory");

            var lst = db.Learnings.Where(model => model.ID_BaiHoc == id).FirstOrDefault();

            return View(lst);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult EditLearn(Learning leGet)
        {

            List<Category> list = db.Categories.ToList();

            ViewBag.List = new SelectList(list, "ID_Category", "TênCategory");

            try
            {

                var leList = db.Learnings.Where(model => model.ID_BaiHoc == leGet.ID_BaiHoc).FirstOrDefault();

                leList.TenBaiHoc = leGet.TenBaiHoc;

                leList.Link = leGet.Link;

                leList.MoTa = leGet.MoTa;

                leList.ID_Category = leGet.ID_Category;

                db.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }


    }
}

WebsiteHocAVOnline/Areas/ADmin/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebsiteHocAVOnline.Models;

namespace WebsiteHocAVOnline.Areas.ADmin.Controllers
{
    public class UserController : Controller
    {
        DBThiTrucTuyenEntities db = new DBThiTrucTuyenEntities();
        // GET: ADmin/User
        public ActionResult Index()
        {
            return View(db.TaiKhoans.ToList());
        }

        [HttpGet]
        public ActionResult DelUser()
        {
            return View(db.TaiKhoans.ToList());
        }

        [HttpPost]
        public ActionResult DelUser(int id)
        {
            TaiKhoan _id = db.TaiKhoans.Find(id);

            db.TaiKhoans.Remove(_id);

            db.SaveChanges();

            return RedirectToAction("Index");

        }
    }
}

WebsiteHocAVOnline/Controllers/DocumentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebsiteHocAVOnline.Models;

namespace WebsiteHocAVOnline.Controllers
{
    public class DocumentController : Controller
    {
        // GET: Document

        DBThiTrucTuyenEntities db = new DBThiTrucTuyenEntities();
        public ActionResult Index()
        {
            return View(db.TaiLieux.ToList());
        }
    }
}

WebsiteHocAVOnline/Areas/ADmin/Views/Shared/_AccountArea.cshtml
 <!-- Nav Item - User Information -->
<li class="nav-item dropdown no-arrow">
    <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <span class="mr-2 d-none d-lg-inline text-gray-600 small">Admin</span>
        <img class="img-profile rounded-circle" src="https://source.unsplash.com/QAB-WJcbgJk/60x60">
    </a>
    <!-- Dropdown - User Information -->
    <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
        <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
            <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400 "></i>
            Đăng xuất
        </a>
    </div>
</li>

  

WebsiteHocAVOnline/Areas/ADmin/Views/Shared/_Layout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>OnLine-Test-AV | Admin</title>

    <!-- Custom fonts for this template -->
    <link href="~/Assets/ADmin/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="~/Assets/ADmin/css/sb-admin-2.min.css" rel="stylesheet">

    <!-- Custom styles for this page -->
    <link href="~/Assets/ADmin/vendor/datatables/dataTables.bootstrap4.min.css" rel="stylesheet">

</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        @RenderPage("_Nav.cshtml")
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                    <!-- Topbar Search -->
                    <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
                        <div class="input-group">
                            <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
                            <div class="input-group-append">
                                <button class="btn btn-primary" type="button">
                                    <i class="fas fa-search fa-sm"></i>
                                </button>
                            </div>
                        </div>
                    </form>

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">

                        <div class="topbar-divider d-none d-sm-block"></div>

                        @RenderPage("_AccountArea.cshtml")

                    </ul>
                </nav>
                <!-- End of Topbar -->
                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!-- Page Heading -->
                    <h1 class="h3 mb-4 text-gray-800">@RenderSection("header", required: false)</h1>
                    <!-- DataTales Example -->


                    <div class="row">
                        @RenderBody()


                    </div>
                </div>
                <!-- /.container-fluid -->
            </div>
            <!-- End of Main Content -->
            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Your Website 2019</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Bạn sẵn sàng để đăng xuất ?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="@Url.Action("LogOut", "System")">Đăng xuất</a>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="~/Assets/ADmin/vendor/jquery/jquery.min.js"></script>
    <script src="~/Assets/ADmin/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="~/Assets/ADmin/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="~/Assets/ADmin/js/sb-admin-2.min.js"></script>

    <!-- Page level plugins -->
    <script src="~/Assets/ADmin/vendor/datatables/jquery.dataTables.min.js"></script>
    <script src="~/Assets/ADmin/vendor/datatables/dataTables.bootstrap4.min.js"></script>

    <!-- Page level custom scripts -->
    <script src="~/Assets/ADmin/js/demo/datatables-demo.js"></script>

</body>

</html>

WebsiteHocAVOnline/Areas/ADmin/Views/Shared/_Nav.cshtml
  <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

        <!-- Sidebar - Brand -->
        <a class="sidebar-brand d-flex align-items-center justify-content-center" href="@Url.Action("Index", "Home")">
            <div class="sidebar-brand-icon">
                <i class="fas fa-user-cog"></i>
            </div>
            <div class="sidebar-brand-text mx-0">OnLine-Test-AV Admin</div>
        </a>

        <!-- Divider -->
        <hr class="sidebar-divider my-0">

        <!-- Nav Item - Dashboard -->
        <li class="nav-item">
            <a class="nav-link" href="" @Url.Action("Index", "Home") ">
                <i class="fa fa-home"></i>
                <span>Trang Chủ</span>
            </a>
        </li>

        <!-- Divider -->
        <hr class="sidebar-divider">

        <!-- Nav Item - Pages Collapse Menu -->
        <li class="nav-item">
            <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
                <i class="fa fa-bookmark"></i>
                <span>Tài Khoản Quản Trị</span>
            </a>
            <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                <div class="bg-white py-2 collapse-inner rounded">
                    <h6 class="collapse-header">Quản Lý TK QTV</h6>
                    <a class="collapse-item" href="@Url.Action("Index", "System")">Thông Tin Tài Khoản</a>
                </div>
        </li>

        <!-- Nav Item - Utilities Collapse Menu -->
        <li class="nav-item">
            <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities" aria-expanded="true" aria-controls="collapseUtilities">
                <i class="fa fa-users"></i>
                <span>Người Dùng</span>
            </a>
            <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities" data-parent="#accordionSidebar">
                <div class="bg-white py-2 collapse-inner rounded">
                    <h6 class="collapse-header">Quản Lý Người Dùng</h6>
                    <a class="collapse-item" href="@Url.Action("Index", "User")">Danh Sách Người Dùng</a>
                </div>
            </div>
        </li>

        <!-- Divider -->
        <hr class="sidebar-divider">
        <!-- Nav Item - Pages Collapse Menu -->
        <li class="nav-item">
            <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="true" aria-controls="collapsePages">
                <i class="fa fa-cogs"></i>
                <span>Bài Học</span>
            </a>
            <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
                <div class="bg-white py-2 collapse-inner rounded">
                    <h6 class="collapse-header">Quản Lý Bài Học</h6>
                    <a class="collapse-item" href="@Url.Action("Index", "Learn")">Chi Tiết Bài Học</a>
                </div>
            </div>
        </li>
        <!-- Nav Item - Pages Collapse Menu -->
        <li class="nav-item">
            <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="true" aria-controls="collapsePages">
                <i class="fa fa-cogs"></i>
                <span>Câu Hỏi</span>
            </a>
            <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
                <div class="bg-white py-2 collapse-inner rounded">
                    <h6 class="collapse-header">Quản Lý Câu Hỏi</h6>
                    <a class="collapse-item" href="@Url.Action("Index", "Question")">Chi Tiết Câu Hỏi</a>
                </div>
            </div>
        </li>

        <!-- Nav Item - Charts -->
        <li class="nav-item">
            <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="true" aria-controls="collapsePages">
                <i class="fa fa-cogs"></i>
                <span>Tài Liệu</span>
            </a>
            <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
                <div class="bg-white py-2 collapse-inner rounded">
                    <h6 class="collapse-header">Quản Lý Tài Liệu</h6>
                    <a class="collapse-item" href="@Url.Action("Index", "Document")">Chi Tiết Tài Liệu</a>
                </div>
            </div>
        </li>
        <!-- Divider -->
        <hr class="sidebar-divider d-none d-md-block">

        <!-- Sidebar Toggler (Sidebar) -->
        <div class="text-center d-none d-md-inline">
            <button class="rounded-circle border-0" id="sidebarToggle"></button>
        </div>

    </ul>
<!-- End of Sidebar -->